'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BillDetail
    Public Property id As Integer
    Public Property price As Decimal
    Public Property tax As Decimal
    Public Property qty As Integer
    Public Property bill_Id As Integer
    Public Property products_Id As Integer

    Public Overridable Property Bill As Bill
    Public Overridable Property Products As Products

End Class
