'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_POS
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_POS")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Bill() As DbSet(Of Bill)
    Public Property BillDetail() As DbSet(Of BillDetail)
    Public Property Brand() As DbSet(Of Brand)
    Public Property Category() As DbSet(Of Category)
    Public Property Client() As DbSet(Of Client)
    Public Property Employee() As DbSet(Of Employee)
    Public Property Products() As DbSet(Of Products)
    Public Property ProductSuppliers() As DbSet(Of ProductSuppliers)
    Public Property Suppliers() As DbSet(Of Suppliers)
    Public Property Warehouse() As DbSet(Of Warehouse)
    Public Property WarehouseProducts() As DbSet(Of WarehouseProducts)

End Class
