'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductSuppliers
    Public Property id As Integer
    Public Property price As Decimal
    Public Property suppliers_Id As Integer
    Public Property products_Id As Integer

    Public Overridable Property Products As Products
    Public Overridable Property Suppliers As Suppliers

End Class
