'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Suppliers
    Public Property id As Integer
    Public Property name As String
    Public Property phone As Integer
    Public Property address As String
    Public Property detail As String

    Public Overridable Property ProductSuppliers As ICollection(Of ProductSuppliers) = New HashSet(Of ProductSuppliers)

End Class
