'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WarehouseProducts
    Public Property id As Integer
    Public Property qtyAvailable As Integer
    Public Property idWarehouse As Integer
    Public Property idProducts As Integer

    Public Overridable Property Products As Products
    Public Overridable Property Warehouse As Warehouse

End Class
